=== FRC4607/Scouting-App/src/common/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "heading": {
      "type": "string"
    },
    "logo": {
      "type": "string"
    },
    "skipTeamSelection": {
      "type": "boolean"
    },
    "pitScoutingMode": {
      "type": "boolean"
    },
    "forceQualifiers": {
      "type": "boolean"
    },
    "pages": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/page"
      }
    }
  },
  "required": [
    "pages"
  ],
  "$defs": {
    "page": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "widgets": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/widget"
          }
        }
      },
      "required": [
        "name",
        "widgets"
      ]
    },
    "validationInequality": {
      "type": "object",
      "properties": {
        "comparison": {
          "type": "string",
          "enum": [
            "less",
            "lessOrEqual",
            "greater",
            "greaterOrEqual",
            "equal"
          ]
        },
        "value": {
          "type": "integer"
        }
      },
      "required": [
        "value"
      ]
    },
    "validationRange": {
      "type": "object",
      "properties": {
        "comparison": {
          "type": "string",
          "enum": [
            "inRange",
            "outOfRange"
          ]
        },
        "value": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      },
      "required": [
        "value"
      ]
    },
    "validation": {
      "type": "object",
      "properties": {
        "comparison": {
          "type": "string",
          "enum": [
            "less",
            "lessOrEqual",
            "greater",
            "greaterOrEqual",
            "equal",
            "inRange",
            "outOfRange"
          ]
        }
      },
      "required": [
        "comparison"
      ],
      "oneOf": [
        {
          "$ref": "#/$defs/validationInequality"
        },
        {
          "$ref": "#/$defs/validationRange"
        }
      ]
    },
    "widgetDropdown": {
      "type": "object",
      "properties": {
        "type": {
          "const": "dropdown"
        },
        "defaultOption": {
          "type": "boolean"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "options"
      ]
    },
    "widgetDropdownWithPictures": {
      "type": "object",
      "properties": {
        "type": {
          "const": "dropdownwithpictures"
        },
        "defaultOption": {
          "type": "boolean"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "files": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "options",
        "files"
      ]
    },
    "widgetHeading": {
      "type": "object",
      "properties": {
        "type": {
          "const": "heading"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetLabel": {
      "type": "object",
      "properties": {
        "type": {
          "const": "label"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetText": {
      "type": "object",
      "properties": {
        "type": {
          "const": "text"
        },
        "placeholder": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetNumber": {
      "type": "object",
      "properties": {
        "type": {
          "const": "number"
        },
        "placeholder": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetCheckbox": {
      "type": "object",
      "properties": {
        "type": {
          "const": "checkbox"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetMultiCheckbox": {
      "type": "object",
      "properties": {
        "type": {
          "const": "multicheckbox"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "options"
      ]
    },
    "widgetPicture": {
      "type": "object",
      "properties": {
        "type": {
          "const": "picture"
        },
        "file": {
          "type": "string"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      },
      "required": [
        "file"
      ]
    },
    "widgetPositions": {
      "type": "object",
      "properties": {
        "type": {
          "const": "positions"
        },
        "file": {
          "type": "string"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "allowMultiple": {
          "type": "boolean"
        },
        "selectRadius": {
          "type": "integer"
        },
        "selectColor": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "file"
      ]
    },
    "widgetRadio": {
      "type": "object",
      "properties": {
        "type": {
          "const": "radio"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "default": {
          "type": "integer"
        }
      },
      "required": [
        "name",
        "options"
      ]
    },
    "widgetSpacer": {
      "type": "object",
      "properties": {
        "type": {
          "const": "spacer"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      }
    },
    "widgetSpinbox": {
      "type": "object",
      "properties": {
        "type": {
          "const": "spinbox"
        },
        "min": {
          "type": "integer"
        },
        "max": {
          "type": "integer"
        },
        "allowKeyboardInput": {
          "type": "boolean"
        },
        "buttonColor": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetStopwatch": {
      "type": "object",
      "properties": {
        "type": {
          "const": "stopwatch"
        },
        "startLabel": {
          "type": "string"
        },
        "lapLabel": {
          "type": "string"
        },
        "stopLabel": {
          "type": "string"
        },
        "maxLaps": {
          "type": "integer"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetAverageStopwatch": {
      "type": "object",
      "properties": {
        "type": {
          "const": "averagestopwatch"
        },
        "startLabel": {
          "type": "string"
        },
        "undoLabel": {
          "type": "string"
        },
        "stopLabel": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetTextarea": {
      "type": "object",
      "properties": {
        "type": {
          "const": "textarea"
        },
        "placeholder": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetToggleGrid": {
      "type": "object",
      "properties": {
        "type": {
          "const": "togglegrid"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "colors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "rowColors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "colColors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "width",
        "height",
        "colors"
      ]
    },
    "widgetPictureUpload": {
      "type": "object",
      "properties": {
        "type": {
          "const": "pictureupload"
        }
      },
      "required": [
        "name"
      ]
    },
    "widgetTeamRanking": {
      "type": "object",
      "properties": {
        "type": {
          "const": "teamranking"
        },
        "alliance": {
          "enum": [
            "red",
            "blue"
          ]
        }
      },
      "required": [
        "alliance"
      ]
    },
    "widgetCheckboxGrid": {
      "type": "object",
      "properties": {
        "type": {
          "const": "checkboxgrid"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "leftOffset": {
          "type": "integer"
        },
        "rightOffset": {
          "type": "integer"
        },
        "topOffset": {
          "type": "integer"
        },
        "bottomOffset": {
          "type": "integer"
        }
      },
      "required": [
        "name"
      ]
    },
    "widget": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "dropdown",
            "dropdownwithpictures",
            "heading",
            "label",
            "text",
            "number",
            "checkbox",
            "multicheckbox",
            "picture",
            "positions",
            "radio",
            "spacer",
            "spinbox",
            "stopwatch",
            "averagestopwatch",
            "textarea",
            "togglegrid",
            "pictureupload",
            "checkboxgrid",
            "teamranking"
          ]
        },
        "prefix": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "displayName": {
          "type": "string"
        },
        "align": {
          "type": "string",
          "enum": [
            "left",
            "center",
            "right"
          ]
        },
        "noLabel": {
          "type": "boolean"
        },
        "row": {
          "type": "integer"
        },
        "col": {
          "type": "integer"
        },
        "rowspan": {
          "type": "integer"
        },
        "colspan": {
          "type": "integer"
        },
        "labelColspan": {
          "type": "integer"
        },
        "validation": {
          "$ref": "#/$defs/validation"
        }
      },
      "required": [
        "type"
      ],
      "oneOf": [
        {
          "$ref": "#/$defs/widgetDropdown"
        },
        {
          "$ref": "#/$defs/widgetDropdownWithPictures"
        },
        {
          "$ref": "#/$defs/widgetHeading"
        },
        {
          "$ref": "#/$defs/widgetLabel"
        },
        {
          "$ref": "#/$defs/widgetText"
        },
        {
          "$ref": "#/$defs/widgetNumber"
        },
        {
          "$ref": "#/$defs/widgetCheckbox"
        },
        {
          "$ref": "#/$defs/widgetMultiCheckbox"
        },
        {
          "$ref": "#/$defs/widgetPicture"
        },
        {
          "$ref": "#/$defs/widgetPositions"
        },
        {
          "$ref": "#/$defs/widgetRadio"
        },
        {
          "$ref": "#/$defs/widgetSpacer"
        },
        {
          "$ref": "#/$defs/widgetSpinbox"
        },
        {
          "$ref": "#/$defs/widgetStopwatch"
        },
        {
          "$ref": "#/$defs/widgetAverageStopwatch"
        },
        {
          "$ref": "#/$defs/widgetTextarea"
        },
        {
          "$ref": "#/$defs/widgetToggleGrid"
        },
        {
          "$ref": "#/$defs/widgetPictureUpload"
        },
        {
          "$ref": "#/$defs/widgetCheckboxGrid"
        },
        {
          "$ref": "#/$defs/widgetTeamRanking"
        }
      ]
    }
  }
}

=== FRC4607/Scouting-App/public/assets/config-ranking.json
{
  "heading": "Rebuilt 2026 (Ranking)",
  "logo": "logo.png",
  "skipTeamSelection": true,
  "pages": [
    {
      "name": "Ranking",
      "widgets": [
        {
          "displayName": "Match Number",
          "name": "match",
          "type": "number",
          "validation": {
            "comparison": "greaterOrEqual",
            "value": 1
          }
        },
        {
          "name": "Note: It's OK to give teams the same rank!",
          "type": "label",
          "col": 2,
          "colspan": 2,
          "labelColspan": 2
        },
        {
          "displayName": "Red Alliance Ranking",
          "name": "red",
          "type": "teamranking",
          "alliance": "red"
        },
        {
          "displayName": "Blue Alliance Ranking",
          "name": "blue",
          "type": "teamranking",
          "alliance": "blue"
        }
      ]
    }
  ]
}

=== FRC4607/Scouting-App/public/assets/archive/2023/config-pits.json
{
  "heading": "Charged Up - 2023 (Pit Scouting)",
  "logo": "logo.png",
  "skipTeamSelection": true,
  "pages": [
    {
      "name": "Team",
      "widgets": [
        {
          "name": "Team Number",
          "type": "number"
        },
        {
          "name": "Drive Coach",
          "type": "text"
        },
        {
          "name": "Driver Names",
          "type": "text"
        }
      ]
    },
    {
      "name": "Robot",
      "widgets": [
        {
          "name": "Height",
          "type": "number"
        },
        {
          "name": "Length",
          "type": "number"
        },
        {
          "name": "Width",
          "type": "number"
        },
        {
          "name": "Wheel-Bumper Distance",
          "type": "number"
        },
        {
          "name": "Weight",
          "type": "number"
        },
        {
          "name": "Drivetrain",
          "type": "dropdown",
          "options": [
            "West Coast",
            "Swerve",
            "Butterfly",
            "Mecanum",
            "Other"
          ]
        },
        {
          "name": "Swerve Motor Type",
          "type": "dropdown",
          "options": [
            "Neo",
            "Falcon",
            "Cim"
          ]
        },
        {
          "name": "Swerve Type",
          "type": "dropdown",
          "options": [
            "No swerve",
            "L1",
            "L2",
            "L3",
            "L4",
            "Neo",
            "Falcon",
            "Custom"
          ]
        },
        {
          "name": "Has Driver Camera",
          "type": "checkbox"
        }
      ]
    },
    {
      "name": "Match Play",
      "widgets": [
        {
          "name": "Cycle Time",
          "type": "number"
        },
        {
          "name": "Can Pick Up",
          "type": "multicheckbox",
          "options": [
            "Ground Upright Cones",
            "Ground Tipped Cones",
            "Ground Cubes",
            "Sub 1 (Direct)",
            "Sub 2 High"
          ]
        },
        {
          "name": "Can Score In",
          "type": "multicheckbox",
          "options": [
            "High",
            "Medium",
            "Low"
          ]
        },
        {
          "name": "Scoring Methods",
          "type": "multicheckbox",
          "options": [
            "Manual",
            "Auto"
          ]
        },
        {
          "name": "Preferred Pickup Location",
          "type": "dropdown",
          "options": [
            "Ground",
            "Sub 1",
            "Sub 2 Low",
            "Sub 2 High"
          ],
          "defaultOption": true
        },
        {
          "name": "Comments",
          "type": "textarea",
          "colspan": 3
        }
      ]
    }
  ]
}

=== FRC4607/Scouting-App/public/assets/config-pits.json
{
  "heading": "Rebuilt 2026 (Pits)",
  "logo": "logo.png",
  "skipTeamSelection": false,
  "pitScoutingMode": true,
  "pages": [
    {
      "name": "Robot",
      "widgets": [
        {
          "displayName": "Scouter Name",
          "name": "scouter_name",
          "type": "text",
          "validation": {
            "comparison": "greater",
            "value": 0
          }
        },
        {
          "displayName": "Programming Language",
          "name": "prog_lang",
          "type": "dropdown",
          "options": [
            "Java",
            "C++",
            "Python",
            "LabVIEW"
          ]
        },
        {
          "displayName": "Battery Brand",
          "name": "bat_brand",
          "type": "dropdown",
          "options": [
            "MK",
            "Duracell",
            "Interstate",
            "Mighty Max",
            "Power Sonic",
            "Other"
          ]
        },
        {
          "displayName": "Other Brand",
          "name": "other_brand",
          "type": "textarea",
          "placeholder": "Only if Other selected above"
        },
        {
          "displayName": "Amount of Batteries",
          "name": "num_bat",
          "type": "number",
          "validation": {
            "comparison": "greaterOrEqual",
            "value": 1
          }
        },
        {
          "displayName": "Battery Condition",
          "name": "bat_condition",
          "type": "textarea",
          "placeholder": "Age, wear, replacement status"
        },
        {
          "displayName": "Robot Height (inches)",
          "name": "height",
          "type": "number"
        },
        {
          "displayName": "Hopper Storage",
          "name": "hopper",
          "type": "checkbox"
        },
        {
          "displayName": "Hopper Storage Size",
          "name": "hopper_size",
          "type": "number",
          "placeholder": "# of game pieces"
        },
        {
          "displayName": "Spare Parts",
          "name": "spare_parts",
          "type": "checkbox"
        },
        {
          "displayName": "Can Go Over Bump?",
          "name": "bump",
          "type": "checkbox"
        },
        {
          "displayName": "Can Go Under Trench?",
          "name": "trench",
          "type": "checkbox"
        },
        {
          "displayName": "Shooter Type",
          "name": "shoot_type",
          "type": "dropdown",
          "options": [
            "Fixed Flywheel Launcher",
            "Turret Flywheel Launcher",
            "Double Fixed Flywheel Launcher",
            "Double Turret Flywheel Launcher",
            "??????"
          ]
        },
        {
          "displayName": "Shooter Notes",
          "name": "shoot_notes",
          "type": "textarea",
          "placeholder": "Range, accuracy, etc."
        },
        {
          "displayName": "Climber Type",
          "name": "climb_type",
          "type": "dropdown",
          "options": [
            "Climber",
            "None"
          ]
        },
        {
          "displayName": "Climber Notes",
          "name": "climb_notes",
          "type": "textarea",
          "placeholder": "Level reached, requirements, reliability, etc."
        },
        {
          "displayName": "Indexer Type",
          "name": "index_type",
          "type": "dropdown",
          "options": [
            "Indexer",
            "No Indexer"
          ]
        },
        {
          "displayName": "Indexer Notes",
          "name": "index_notes",
          "type": "textarea",
          "placeholder": "Capacity, speed, reliability (no jams), etc."
        },
        {
          "displayName": "Feed Rate (fuel/sec)",
          "name": "feed_rate",
          "type": "number"
        },
        {
          "displayName": "Intake",
          "name": "intake",
          "type": "dropdown",
          "options": [
            "None",
            "Ground",
            "?"
          ]
        },
        {
          "displayName": "Intake Speed (fuel/sec)",
          "name": "intake_speed",
          "type": "number"
        },
        {
          "displayName": "Pre-Match Checklist",
          "name": "pre_checklist",
          "type": "checkbox"
        },
        {
          "displayName": "How Do They Not Break Down",
          "name": "not_breakdown",
          "type": "textarea",
          "placeholder": "Strategies, practices"
        },
        {
          "displayName": "Sensitive Components Protected",
          "name": "components_protected",
          "type": "checkbox"
        },
        {
          "displayName": "Breaker Cover",
          "name": "breaker_cover",
          "type": "checkbox"
        }
      ]
    },
    {
      "name": "Pictures",
      "widgets": [
        {
          "displayName": "Robot Full View",
          "name": "pic_robot_full",
          "type": "pictureupload"
        },
        {
          "displayName": "Drivetrain",
          "name": "pic_drivetrain",
          "type": "pictureupload"
        },
        {
          "displayName": "Intake Mechanism",
          "name": "pic_intake",
          "type": "pictureupload"
        },
        {
          "displayName": "Shooter/Scoring Mechanism",
          "name": "pic_shooter",
          "type": "pictureupload"
        },
        {
          "displayName": "Climber Mechanism",
          "name": "pic_climber",
          "type": "pictureupload"
        },
        {
          "displayName": "Electronics/Wiring",
          "name": "pic_electronics",
          "type": "pictureupload"
        },
        {
          "displayName": "Battery Storage Area",
          "name": "pic_battery",
          "type": "pictureupload"
        },
        {
          "displayName": "Battery Charging Area",
          "name": "pic_battery_charging",
          "type": "pictureupload"
        },
        {
          "displayName": "Additional Photos",
          "name": "pic_misc",
          "type": "pictureupload"
        }
      ]
    }
  ]
}
